language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - nvm install
  - nvm use
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements-dev.txt
script:
  - cp django_airavata/settings_local.py.sample django_airavata/settings_local.py
<<<<<<< HEAD
  - cd ../../../airavata-django-portal/
=======
  - cd ./airavata-django-portal/
>>>>>>> ebf61998fbdc13b822ee32c5fd49ccd7d2dc0347
  - python manage.py migrate
  - python manage.py check
  - flake8 .
  - ./lint_js.sh
  - ./build_js.sh
  - ./test_js.sh
  # Need to build the frontend client before running some of the Django tests
  # that use the Django test Client
  - ./runtests.py
